version: "3.9"

services:
  database:
    image: postgres
    container_name: database_logger
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=huxx_logger
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: huxx-logger
    restart: always
    ports:
      - 3000:3000
      - 9229:9229 #debug
    volumes:
      - .:/usr/app
    links:
      -database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local